Repository iotaledger/iota.rs, pull requests merged in 2019-09, with the labels that each got.

#19 infra: add format check on CI
  .travis.yml
  iota-crypto/kerl.rs
Labels: A-infra, S-ready-for-review

#18 client: fix bundle index
  iota-model/bundle.rs
  src/iota_api.rs
Labels: A-client, C-bug, S-ready-for-review

#17 client: merge iota_api into iota_client
  iota-client/client.rs
  iota-client/core/add_neighbors.rs
  iota-client/core/attach_to_tangle.rs
  iota-client/core/broadcast_transactions.rs
  iota-client/core/check_consistency.rs
  iota-client/core/find_transactions.rs
  iota-client/core/get_balances.rs
  iota-client/core/get_inclusion_states.rs
  iota-client/core/get_neighbors.rs
  iota-client/core/get_node_info.rs
  iota-client/core/get_tips.rs
  iota-client/core/get_transactions_to_approve.rs
  iota-client/core/get_trytes.rs
  iota-client/core/interrupt_attaching_to_tangle.rs
  iota-client/core/mod.rs
  iota-client/core/remove_neighbors.rs
  iota-client/core/store_transactions.rs
  iota-client/core/were_addresses_spent_from.rs
  iota-client/extended/get_bundle.rs
  iota-client/extended/get_inputs.rs
  iota-client/extended/get_new_address.rs
  iota-client/extended/mod.rs
  iota-client/extended/prepare_transfers.rs
  iota-client/extended/send_transfers.rs
  iota-client/extended/send_trytes.rs
  iota-client/extended/store_and_broadcast.rs
  iota-client/extended/traverse_bundle.rs
  iota-client/get_node_info.rs
  iota-client/lib.rs
  iota-client/remove_neighbors.rs
  iota-client/responses.rs
  iota-client/were_addresses_spent_from.rs
  src/iota_api.rs
  src/lib.rs
  src/prelude.rs
Labels: A-client, S-ready-for-review

#24 Infra: add git commit hook.
  .travis.yml
  Cargo.toml
Labels: A-infra, C-enhancement, P-high, S-ready-for-review
