Repository iotaledger/iota.rs, pull requests merged in 2022-02, with the labels that each got.

#793 examples: fix unnecessary use of `to_vec`
  .github/workflows/examine-core.yml
  examples/custom_payload.rs
  src/api/message_builder.rs
  src/client.rs
Labels: scope:core, type:fix

#796 bindings/python: apply clippy fixes
  .github/workflows/examine-python-bindings.yml
  bindings/python/native/src/client/types.rs
Labels: scope:ci, type:fix

#797 bindings/wasm: bypass clippy::needless_borrow
  bindings/wasm/native/Cargo.toml
  bindings/wasm/native/src/client.rs
Labels: scope:ci, type:fix

#800 Bindings/java: fix seed parse
  bindings/java/README.md
  bindings/java/examples/basic-app/src/main/java/org/example/ExampleApp.java
  bindings/java/examples/basic-app/src/test/java/org/example/LibraryTest.java
  bindings/java/native/pom.xml
  bindings/java/native/src/classes/address.rs
  bindings/java/native/src/classes/client/balance.rs
  bindings/java/native/src/classes/client/full_node_api.rs
  bindings/java/native/src/classes/message.rs
  bindings/java/native/src/classes/mod.rs
  bindings/java/native/src/java_glue.rs.in
Labels: scope:java, type:fix

#794 bindings/java/native: fix clippy & rustfmt warnings
  .github/workflows/examine-java-bindings.yml
  bindings/java/native/src/bee_types/index.rs
  bindings/java/native/src/bee_types/input.rs
  bindings/java/native/src/bee_types/milestone.rs
  bindings/java/native/src/bee_types/output.rs
  bindings/java/native/src/bee_types/payloads.rs
  bindings/java/native/src/bee_types/receipt.rs
  bindings/java/native/src/bee_types/transaction.rs
  bindings/java/native/src/bee_types/treasury.rs
  bindings/java/native/src/bee_types/unlock.rs
  bindings/java/native/src/classes/address.rs
  bindings/java/native/src/classes/client/balance.rs
  bindings/java/native/src/classes/client/client_builder.rs
  bindings/java/native/src/classes/client/full_node_api.rs
  bindings/java/native/src/classes/client/mqtt.rs
  bindings/java/native/src/classes/message.rs
  bindings/java/native/src/classes/mod.rs
  bindings/java/native/src/classes/prepared.rs
  bindings/java/native/src/java_glue.rs
  bindings/java/native/src/java_glue.rs.in
  bindings/java/native/src/jni_c_header.rs
Labels: scope:java, type:fix

#802 Fix sync feature
  Cargo.lock
  Cargo.toml
Labels: scope:core, type:fix

#792 bindings/nodejs: fix minPoWScore assertion on devnet
  .github/workflows/examine-nodejs-bindings.yml
  .github/workflows/examine-wasm-bindings.yml
  bindings/nodejs/tests/client.js
  bindings/wasm/tests/client.js
Labels: scope:nodejs, status:blocked, type:fix

#803 Make TLS optional
  Cargo.toml
  bindings/wasm/native/Cargo.toml
Labels: type:enhancement, scope:core

#804 Remove pow-fallback feature and add a method to the client builder
  Cargo.toml
  bindings/java/native/Cargo.toml
  bindings/nodejs/native/Cargo.toml
  bindings/python/native/Cargo.toml
  bindings/wasm/native/Cargo.toml
  src/api/message_builder.rs
  src/builder.rs
  src/client.rs
Labels: scope:core, type:fix

#814 Update discord channel names
  README.md
Labels: scope:misc

#817 Update bug report template
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: scope:misc

#819 Add a task creation template
  .github/ISSUE_TEMPLATE/create-task.yml
Labels: scope:misc

#820 Add a pull request template
  .github/pull_request_template.md
Labels: scope:misc

#822 fix/java: Removed old android build file
  bindings/java/native/build_android.rs
Labels: scope:java

#826 Trim mnemonic, because empty spaces could create a different seed
  src/client.rs
  tests/mnemonic.rs
Labels: type:fix, type:tests

#823 feat: bech32 is bip-173 compliant
  src/node/mqtt.rs
  src/node_manager.rs
Labels: good first issue, type:feature
