Repository iotaledger/iota.rs, pull requests merged in 2022-05, with the labels that each got.

#966 Use Id::null instead of from null arrays
  Cargo.lock
  Cargo.toml
  examples/outputs/alias.rs
  examples/outputs/all.rs
  examples/outputs/all_automatic_input_selection.rs
  examples/outputs/foundry.rs
  examples/outputs/nft.rs
Labels: scope:core, priority:3, type:chore

#969 Fix automatic input selection
  src/api/message_builder/input_selection/mod.rs
Labels: network:shimmer, type:fix

#971 Merge mainnet branch
  documentation/docs/getting_started.md
  documentation/docs/overview.md
  documentation/docs/welcome.md
  documentation/static/img/Banner/banner_client_lib.png
  documentation/static/img/Banner/banner_client_lib_getting_started.png
  documentation/static/img/Banner/banner_client_lib_overview.png
Labels: scope:docs, network:mainnet

#968 Support milestone id endpoint changes
  examples/message_time.rs
  src/client.rs
  src/message_interface/client_method.rs
  src/message_interface/message_handler.rs
  src/node_api/core/routes.rs
  tests/node_api.rs
Labels: network:shimmer

#964 Add `--all-features` to cargo udeps workflows
  .github/workflows/examine-core.yml
  .github/workflows/examine-java-bindings.yml
  .github/workflows/examine-nodejs-bindings.yml
  .github/workflows/examine-python-bindings.yml
  .github/workflows/examine-wasm-bindings.yml
Labels: scope:ci

#965 Add StoreMnemonic and load Stronghold snapshot in message_interface
  bindings/nodejs/native/Cargo.lock
  bindings/nodejs/native/Cargo.toml
  bindings/nodejs/package.json
  bindings/nodejs/tests/client.js
  bindings/nodejs/tests/mqtt.js
  bindings/python/native/Cargo.lock
  src/message_interface/client_method.rs
  src/message_interface/message_handler.rs
  src/message_interface/mod.rs
Labels: network:shimmer, scope:message_interface

#960 Accept SecretManagerDto instead of String in message interface
  src/message_interface/client_method.rs
  src/message_interface/message_handler.rs
  src/message_interface/mod.rs
  src/secret/mod.rs
  src/secret/types.rs
Labels: network:shimmer

#974 Add aliasAddress query parameter
  src/node_api/indexer/query_parameters.rs
Labels: network:shimmer

#972 Add new address generation tests
  tests/addresses.rs
  tests/fixtures/test_vectors.json
Labels: network:shimmer, type:tests

#980 Bump bee revision
  Cargo.lock
  Cargo.toml
Labels: scope:dependencies, network:shimmer, priority:2, type:chore

#979 Fix addresses test
  tests/addresses.rs
Labels: network:shimmer

#981 Update binding Cargo.lock files
  bindings/nodejs/native/Cargo.lock
  bindings/python/native/Cargo.lock
Labels: network:shimmer

#977 Add OutputMetadata type
  src/api/message_builder/input_selection/automatic.rs
  src/api/message_builder/input_selection/manual.rs
  src/api/message_builder/input_selection/mod.rs
  src/api/message_builder/input_selection/output_data.rs
  src/api/message_builder/input_selection/remainder.rs
  src/api/message_builder/transaction.rs
  src/secret/mod.rs
  src/secret/types.rs
Labels: scope:core, network:shimmer, priority:3, type:enhancement

#853 docs: add a branch section to README
  README.md
Labels: scope:project, type:documentation

#983 Fix get message raw
  bindings/java/native/src/java_glue.rs.in
  bindings/python/README.md
  documentation/docs/libraries/java/api_reference.md
  documentation/docs/libraries/python/api_reference.md
  src/client.rs
  src/node_api/core/routes.rs
  src/node_manager/http_client.rs
  src/node_manager/mod.rs
Labels: network:shimmer, type:fix

#986 Remove useless client method forwards
  examples/custom_inputs.rs
  examples/custom_remainder_address.rs
  examples/indexer.rs
  examples/outputs/all.rs
  examples/outputs/foundry.rs
  src/api/message_builder/input_selection/automatic.rs
  src/client.rs
  src/node_api/core/mod.rs
  src/node_api/core/routes.rs
  src/node_api/high_level/address.rs
  src/node_api/indexer/mod.rs
  src/node_api/indexer/routes.rs
Labels: scope:core, priority:3, type:chore

#987 Create dir before writing stronghold snapshot if it doesn't exist
  src/stronghold/mod.rs
  tests/secret_manager.rs
Labels: network:shimmer, type:fix

#997 Add remainder to PreparedTransactionData
  Cargo.toml
  bindings/java/native/src/classes/message.rs
  bindings/java/native/src/classes/prepared.rs
  bindings/java/native/src/java_glue.rs.in
  bindings/nodejs/examples/offline_signing/example_prepared_transaction.json
  bindings/wasm/examples/offline_signing/example_prepared_transaction.json
  examples/ledger_nano.rs
  examples/offline_signing/2_transaction_signing.rs
  examples/offline_signing/3_send_message.rs
  src/api/address.rs
  src/api/message_builder/input_selection/manual.rs
  src/api/message_builder/input_selection/mod.rs
  src/api/message_builder/input_selection/remainder.rs
  src/api/message_builder/input_selection/types.rs
  src/api/message_builder/transaction.rs
  src/api/types.rs
  src/error.rs
  src/message_interface/mod.rs
  src/secret/ledger_nano.rs
  src/secret/mnemonic.rs
  src/secret/mod.rs
  src/secret/types.rs
  src/stronghold/secret.rs
Labels: network:shimmer

#993 API spring cleaning
  Cargo.lock
  Cargo.toml
  documentation/docs/node_api_core.md
  examples/01_get_info.rs
  examples/08_data_message.rs
  examples/message_time.rs
  examples/node_api_core/02_get_info.rs
  examples/node_api_core/03_get_tips.rs
  examples/node_api_core/04_post_message.rs
  examples/node_api_core/05_post_message_raw.rs
  examples/node_api_core/06_get_message.rs
  examples/node_api_core/07_get_message_raw.rs
  examples/node_api_core/08_get_message_metadata.rs
  examples/node_api_core/09_get_message_children.rs
  examples/node_api_core/15_get_treasury.rs
  examples/node_api_core/18_get_milestone_by_id.rs
  examples/node_api_core/19_get_milestone_by_id_raw.rs
  src/api/message_builder/mod.rs
  src/api/message_builder/pow/mod.rs
  src/client.rs
  src/error.rs
  src/message_interface/client_method.rs
  src/message_interface/message_handler.rs
  src/message_interface/response_type.rs
  src/node_api/core/routes.rs
  src/node_manager/http_client.rs
  src/node_manager/mod.rs
  tests/node_api.rs
Labels: network:shimmer, type:documentation, type:feature, type:refactor

#791 Add test for address generation with a mnemonic
  bindings/nodejs/tests/client.js
  bindings/python/native/tests/fixtures/test_vectors.json
  bindings/python/native/tests/test_full_node_api.py
  bindings/python/native/tests/test_high_level_api.py
  bindings/python/native/tests/test_mqtt.py
  bindings/wasm/tests/client.js
  tests/addresses.rs
  tests/fixtures/test_vectors.json
Labels: scope:core, type:tests

#1000 More examples and changes
  Cargo.toml
  documentation/docs/node_api_core.md
  examples/node_api_core/13_get_receipts.rs
  examples/node_api_core/14_get_receipts_migrated_at.rs
  src/client.rs
  src/node_manager/builder.rs
  src/node_manager/http_client.rs
  src/node_manager/mod.rs
Labels: network:shimmer

#995 Stronghold Integration and Message Interface Improvements
  Cargo.toml
  bindings/nodejs/src/message_handler.rs
  src/message_interface/message.rs
  src/message_interface/message_handler.rs
  src/message_interface/mod.rs
  src/message_interface/response.rs
  src/message_interface/response_type.rs
  src/secret/mod.rs
  src/secret/types.rs
  src/stronghold/mod.rs
  tests/addresses.rs
Labels: scope:core, network:shimmer, type:enhancement, type:refactor, scope:message_interface

#1001 Add PlaceholderSecretManager
  src/error.rs
  src/secret/mod.rs
  src/secret/placeholder.rs
Labels: network:shimmer, type:feature

#1002 Indexer API query parameters changes and checks
  bindings/nodejs/types/queryParameters.ts
  examples/04_get_address_outputs.rs
  examples/05_get_address_balance.rs
  examples/custom_inputs.rs
  examples/custom_remainder_address.rs
  examples/indexer.rs
  examples/outputs/all.rs
  examples/outputs/foundry.rs
  examples/outputs/nft.rs
  examples/quorum.rs
  examples/send_all.rs
  src/api/consolidation.rs
  src/api/message_builder/input_selection/automatic.rs
  src/client.rs
  src/error.rs
  src/message_interface/client_method.rs
  src/message_interface/message_handler.rs
  src/node_api/high_level/address.rs
  src/node_api/indexer/mod.rs
  src/node_api/indexer/query_parameters.rs
  src/node_api/indexer/responses.rs
  src/node_api/indexer/routes.rs
  tests/node_api.rs
Labels: network:shimmer

#1008 Add and use SignedTransactionData for offline signing
  examples/offline_signing/2_transaction_signing.rs
  examples/offline_signing/3_send_message.rs
  src/api/types.rs
Labels: network:shimmer, type:enhancement

#1011 Add cargo profiles
  Cargo.toml
Labels: network:shimmer, type:chore

#1009 Make QueryParameters a sorted Vec
  src/node_api/indexer/query_parameters.rs
Labels: scope:core, network:shimmer, type:chore

#989 Add output metadata endpoint
  src/api/block_builder/input_selection/automatic.rs
  src/api/block_builder/input_selection/manual.rs
  src/api/block_builder/input_selection/output_data.rs
  src/client.rs
  src/message_interface/client_method.rs
  src/message_interface/message_handler.rs
  src/message_interface/response.rs
  src/node_api/core/routes.rs
  src/node_api/mqtt/types.rs
  src/node_manager/builder.rs
  src/secret/types.rs
Labels: scope:core, priority:2, type:feature

#1018 Remove MessageType
  bindings/nodejs/src/message_handler.rs
  bindings/python/native/iota_client/common.py
  bindings/python/native/src/lib.rs
  src/message_interface/message.rs
  src/message_interface/message_handler.rs
  src/message_interface/message_type.rs
  src/message_interface/mod.rs
  tests/addresses.rs
Labels: network:shimmer, scope:message_interface

#1020 Derive more traits for types
  Cargo.lock
  Cargo.toml
  src/api/types.rs
  src/secret/types.rs
Labels: network:shimmer

#1029 Add output builders to message interface
  src/message_interface/client_method.rs
  src/message_interface/message_handler.rs
  src/message_interface/mod.rs
  src/message_interface/output_builder.rs
  src/message_interface/response.rs
Labels: network:shimmer, scope:message_interface

#1030 Fix primary_pow_node usage
  .changes/primary-pow-node.md
  src/node_manager.rs
Labels: network:mainnet, type:fix

#1031 Fix primary_pow_node usage
  src/node_manager/mod.rs
Labels: network:shimmer, type:fix

#1039 Update examples
  Cargo.toml
  documentation/docs/libraries/rust/examples.mdx
  examples/00_mnemonic.rs
  examples/01_generate_addresses.rs
  examples/02_get_address_balance.rs
  examples/03_simple_block.rs
  examples/04_get_block_metadata.rs
  examples/05_data_block.rs
  examples/06_transaction.rs
  examples/07_mqtt.rs
  examples/block_time.rs
  examples/consolidation.rs
  examples/indexer.rs
  examples/node_api_indexer/00_get_basic_outputs.rs
  examples/output.rs
  examples/send_all.rs
  examples/split_funds.rs
  examples/transaction.rs
Labels: network:shimmer
