Repository iotaledger/iota.rs, pull requests merged in 2022-01, with the labels that each got.

#787 chore: Fix clippy error
  src/client.rs
Labels: type:enhancement, scope:project

#785 .github/workflows: refresh
  .github/actions/setup-clang/action.yml
  .github/actions/setup-rust/action.yml
  .github/workflows/README.md
  .github/workflows/audit.yml
  .github/workflows/build_and_test.yml
  .github/workflows/clippy.yml
  .github/workflows/covector-status.yml
  .github/workflows/covector-version-or-publish.yml
  .github/workflows/covector.yml
  .github/workflows/examine-core.yml
  .github/workflows/examine-java-bindings.yml
  .github/workflows/examine-nodejs-bindings.yml
  .github/workflows/examine-python-bindings.yml
  .github/workflows/examine-wasm-bindings.yml
  .github/workflows/format.yml
  .github/workflows/python-bindings-publish.yml
  .github/workflows/python_binding_publish.yml
  .github/workflows/udeps.yml
Labels: scope:ci

#788 Update Wasm dependencies
  Cargo.lock
  Cargo.toml
  src/api/message_builder.rs
  src/client.rs
Labels: scope:wasm
