Repository iotaledger/iota.rs, pull requests merged in 2022-03, with the labels that each got.

#832 Cleanup sign_transaction_essence
  src/signing/mnemonic.rs
Labels: network:shimmer

#828 Use windows-2019 for nodejs binding workflow
  .github/workflows/examine-nodejs-bindings.yml
Labels: scope:ci

#831 Implement Stronghold-as-a-Signer
  Cargo.lock
  Cargo.toml
  examples/stronghold.rs
  src/error.rs
  src/signing/mod.rs
  src/signing/stronghold.rs
  src/signing/types.rs
  tests/signer.rs
Labels: scope:core, type:feature

#835 .github/workflow: fix covector (#828)
  .github/workflows/covector.yml
Labels: scope:ci, type:fix

#837 Log time for GET requests
  src/node_manager.rs
Labels: scope:core, network:mainnet

#841 Add storage deposit checks
  Cargo.lock
  Cargo.toml
  examples/offline_signing/2_transaction_signing.rs
  examples/outputs/all.rs
  examples/outputs/all_automatic_input_selection.rs
  examples/outputs/foundry.rs
  src/api/message_builder/input_selection/automatic.rs
  src/api/message_builder/input_selection/manual.rs
  src/api/message_builder/input_selection/mod.rs
  src/api/message_builder/input_selection/output_data.rs
  src/api/message_builder/mod.rs
  src/api/message_builder/pow/mod.rs
  src/api/message_builder/transaction.rs
  src/builder.rs
  src/client.rs
  src/error.rs
  src/signing/mnemonic.rs
  src/utils.rs
Labels: scope:core, network:shimmer

#843 Merge transaction signing code from signers
  src/signing/mnemonic.rs
  src/signing/mod.rs
  src/signing/stronghold.rs
Labels: scope:core, network:shimmer, type:refactor

#839 Update lock files, fix RUSTSEC-2022-0013
  Cargo.lock
  Cargo.toml
  bindings/java/Cargo.lock
  bindings/nodejs/native/Cargo.lock
  bindings/python/native/Cargo.lock
  bindings/wasm/native/Cargo.lock
Labels: scope:dependencies, type:fix

#846 bindings/java: drop RefCells before awaits
  bindings/java/native/src/classes/client/client_builder.rs
Labels: scope:java, type:fix

#849 Update QueryParameters
  examples/outputs/all.rs
  examples/outputs/all_automatic_input_selection.rs
  examples/outputs/basic.rs
  src/api/consolidation.rs
  src/api/message_builder/input_selection/automatic.rs
  src/client.rs
  src/node_api/high_level/address.rs
  src/node_api/indexer_api/query_parameters.rs
  src/node_api/indexer_api/routes.rs
Labels: scope:core, network:shimmer

#845 signing: provide default implementations
  examples/stronghold.rs
  src/error.rs
  src/signing/mnemonic.rs
  src/signing/mod.rs
  src/signing/stronghold.rs
  tests/signer.rs
Labels: scope:core, network:shimmer, type:refactor

#848 Fix request_timeout
  src/builder.rs
  src/node_manager.rs
Labels: network:mainnet, type:fix

#851 Fix wasm feature
  src/node_manager.rs
Labels: scope:wasm, network:mainnet, type:fix

#855 Downgrade zeroize
  Cargo.toml
Labels: network:mainnet

#859 Add native tokens when foundry got created
  src/api/message_builder/input_selection/native_token_helpers.rs
Labels: network:shimmer, type:fix

#861 Testnet4 changes
  Cargo.lock
  Cargo.toml
  examples/outputs/all.rs
  examples/outputs/all_automatic_input_selection.rs
  examples/outputs/foundry.rs
  src/api/message_builder/input_selection/native_token_helpers.rs
  src/api/message_builder/mod.rs
  src/error.rs
  src/node_api/core_api/routes.rs
  src/node_api/indexer_api/mod.rs
Labels: network:shimmer

#879 Update networkinfo with wasm feature every time
  src/api/message_builder/transaction.rs
  src/client.rs
Labels: network:shimmer

#880 Bee message dtos
  Cargo.lock
  Cargo.toml
  examples/outputs/alias.rs
  examples/outputs/all.rs
  examples/outputs/all_automatic_input_selection.rs
  examples/outputs/foundry.rs
  examples/outputs/nft.rs
  examples/send_all.rs
  src/api/message_builder/input_selection/mod.rs
  src/api/message_builder/input_selection/native_token_helpers.rs
  src/api/message_builder/input_selection/output_data.rs
  src/api/message_builder/mod.rs
  src/api/message_builder/transaction.rs
  src/error.rs
  src/node_api/core_api/routes.rs
  src/signing/mod.rs
Labels: network:shimmer

#850 chore (nodejs): use local @iota/client package in package.json
  bindings/nodejs/.gitignore
  bindings/nodejs/package-lock.json
  bindings/nodejs/package.json
  bindings/nodejs/scripts/create-package-json.js
Labels: scope:nodejs, type:chore
