Repository iotaledger/iota.rs, pull requests merged in 2022-06, with the labels that each got.

#1034 Add Method to Change Stronghold Password
  src/stronghold/mod.rs
Labels: scope:core, network:shimmer, type:enhancement

#1037 Update preparedTransactionData type
  bindings/nodejs/examples/01_get_info.ts
  bindings/nodejs/examples/02_mnemonic.ts
  bindings/nodejs/examples/03_generate_addresses.ts
  bindings/nodejs/examples/04_get_address_outputs.ts
  bindings/nodejs/examples/04b_get_output.ts
  bindings/nodejs/examples/05_get_address_balance.ts
  bindings/nodejs/examples/06_simple_block.ts
  bindings/nodejs/examples/07_get_block_data.ts
  bindings/nodejs/examples/08_data_block.ts
  bindings/nodejs/examples/09_transaction.ts
  bindings/nodejs/examples/consolidation.ts
  bindings/nodejs/examples/offline_signing/0_address_generation.ts
  bindings/nodejs/examples/offline_signing/1_transaction_preparation.ts
  bindings/nodejs/examples/offline_signing/2_transaction_signing.ts
  bindings/nodejs/examples/offline_signing/3_send_block.ts
  bindings/nodejs/examples/offline_signing/example_prepared_transaction.json
  bindings/nodejs/examples/offline_signing/example_signed_transaction.json
  bindings/nodejs/lib/Client.ts
  bindings/nodejs/package.json
  bindings/nodejs/test/client/examples.spec.ts
  bindings/nodejs/test/client/infoMethods.spec.ts
  bindings/nodejs/test/client/messageMethods.spec.ts
  bindings/nodejs/test/client/milestoneMethods.spec.ts
  bindings/nodejs/test/client/offlineSigningExamples.spec.ts
  bindings/nodejs/test/client/outputBuilders.spec.ts
  bindings/nodejs/test/client/utilityMethods.spec.ts
  bindings/nodejs/test/client/utxoMethods.spec.ts
  bindings/nodejs/test/fixtures/preparedTransaction.json
  bindings/nodejs/types/bridge/client.ts
  bindings/nodejs/types/bridge/index.ts
  bindings/nodejs/types/generateAddressesOptions.ts
  bindings/nodejs/types/generateBlockOptions.ts
  bindings/nodejs/types/index.ts
  bindings/nodejs/types/nodeInfo.ts
  bindings/nodejs/types/outputBuilderOptions/aliasOutputOptions.ts
  bindings/nodejs/types/outputBuilderOptions/basicOutputOptions.ts
  bindings/nodejs/types/outputBuilderOptions/foundryOutputOptions.ts
  bindings/nodejs/types/outputBuilderOptions/index.ts
  bindings/nodejs/types/outputBuilderOptions/nftOutputOptions.ts
  bindings/nodejs/types/preparedTransactionData.ts
  bindings/nodejs/types/queryParameters.ts
  bindings/nodejs/yarn.lock
  src/client.rs
  src/message_interface/client_method.rs
Labels: scope:nodejs, network:shimmer

#1041 Add checks to set_password() and update Stronghold example
  examples/00_mnemonic.rs
  examples/stronghold.rs
  src/error.rs
  src/stronghold/mod.rs
Labels: network:shimmer

#1049 Accept Vec instead of slice
  src/stronghold/mod.rs
Labels: network:shimmer

#1051 Fx milestone topic in example
  examples/07_mqtt.rs
Labels: network:shimmer

#1050 Bump version
  Cargo.lock
  Cargo.toml
  README.md
  bindings/nodejs/native/Cargo.lock
  bindings/nodejs/native/src/classes/client/api.rs
  bindings/python/native/Cargo.lock
  documentation/docs/libraries/rust/getting_started.md
Labels: network:mainnet

#1054 Remove children endpoint
  Cargo.toml
  bindings/java/native/src/classes/message.rs
  bindings/java/native/src/java_glue.rs.in
  bindings/nodejs/README.md
  bindings/nodejs/lib/Client.ts
  bindings/nodejs/test/client/messageMethods.spec.ts
  bindings/nodejs/types/bridge/client.ts
  bindings/nodejs/types/bridge/index.ts
  bindings/python/README.md
  bindings/python/native/iota_client/_node_core_api.py
  bindings/wasm/docs/api-reference.md
  bindings/wasm/examples/node.js
  bindings/wasm/native/src/message_getter.rs
  bindings/wasm/tests/client.js
  documentation/docs/libraries/java/api_reference.md
  documentation/docs/libraries/nodejs/api_reference.md
  documentation/docs/libraries/python/api_reference.md
  documentation/docs/libraries/wasm/api_reference.md
  documentation/docs/node_api_core.md
  examples/node_api_core/08_get_block_children.rs
  src/message_interface/client_method.rs
  src/message_interface/message_handler.rs
  src/message_interface/response.rs
  src/node_api/core/routes.rs
  tests/node_api.rs
Labels: network:shimmer

#1055 feat (Python binding): Make API calls up to date
  bindings/python/native/examples/example.py
  bindings/python/native/iota_client/_base_api.py
  bindings/python/native/iota_client/_high_level_api.py
  bindings/python/native/iota_client/_node_core_api.py
  bindings/python/native/iota_client/_node_indexr_api.py
  bindings/python/native/iota_client/_utils.py
  bindings/python/native/iota_client/client.py
Labels: scope:python, network:shimmer

#1061 Add conflict reason to error message
  src/error.rs
Labels: network:shimmer

#1065 add micro-transaction example
  examples/outputs/microtransaction.rs
Labels: network:shimmer

#1073 Fix wasm target
  Cargo.toml
  src/api/block_builder/pow/mod.rs
  src/message_interface/message_handler.rs
  src/message_interface/mod.rs
  src/node_api/core/mod.rs
  src/node_api/core/routes.rs
Labels: scope:wasm, network:shimmer

#1071 Remove MilestoneIndex from unlock conditions and QueryParameters
  Cargo.lock
  Cargo.toml
  bindings/nodejs/types/queryParameters.ts
  examples/offline_signing/3_send_block.rs
  examples/outputs/all.rs
  examples/outputs/all_automatic_input_selection.rs
  examples/outputs/basic.rs
  examples/outputs/microtransaction.rs
  src/api/block_builder/transaction.rs
  src/client.rs
  src/node_api/indexer/query_parameters.rs
  src/node_api/indexer/routes.rs
Labels: network:shimmer

#1081 Update bee rev for new nodeinfo and fix unlock conditions in examples
  Cargo.lock
  Cargo.toml
  examples/outputs/all.rs
  examples/outputs/all_automatic_input_selection.rs
  examples/outputs/basic.rs
  src/error.rs
  src/node_api/core/routes.rs
Labels: network:shimmer

#1083 use `dotenv` for urls in all examples
  .env.example
  Cargo.toml
  examples/01_generate_addresses.rs
  examples/02_get_address_balance.rs
  examples/03_simple_block.rs
  examples/04_get_block_metadata.rs
  examples/05_data_block.rs
  examples/06_transaction.rs
  examples/block_time.rs
  examples/consolidation.rs
  examples/custom_inputs.rs
  examples/custom_parent.rs
  examples/custom_payload.rs
  examples/custom_remainder_address.rs
  examples/get_funds.rs
  examples/indexer.rs
  examples/inputs_from_transaction_id.rs
  examples/ledger_nano.rs
  examples/node_api_core/00_get_health.rs
  examples/node_api_core/01_get_info.rs
  examples/node_api_core/02_get_tips.rs
  examples/node_api_core/03_post_block.rs
  examples/node_api_core/04_post_block_raw.rs
  examples/node_api_core/05_get_block.rs
  examples/node_api_core/06_get_block_raw.rs
  examples/node_api_core/07_get_block_metadata.rs
  examples/node_api_core/12_get_receipts.rs
  examples/node_api_core/13_get_receipts_migrated_at.rs
  examples/node_api_core/14_get_treasury.rs
  examples/node_api_core/17_get_milestone_by_id.rs
  examples/node_api_core/18_get_milestone_by_id_raw.rs
  examples/node_api_core/19_get_utxo_changes_by_id.rs
  examples/node_api_core/20_get_milestone_by_index.rs
  examples/node_api_core/21_get_milestone_by_index_raw.rs
  examples/node_api_core/22_get_utxo_changes_by_index.rs
  examples/node_api_indexer/00_get_basic_outputs.rs
  examples/node_api_indexer/01_get_nft_outputs.rs
  examples/node_api_indexer/02_get_alias_outputs.rs
  examples/node_api_indexer/03_get_foundry_outputs.rs
  examples/offline_signing/0_address_generation.rs
  examples/offline_signing/1_transaction_preparation.rs
  examples/offline_signing/3_send_block.rs
  examples/output.rs
  examples/outputs/alias.rs
  examples/outputs/all.rs
  examples/outputs/all_automatic_input_selection.rs
  examples/outputs/basic.rs
  examples/outputs/foundry.rs
  examples/outputs/microtransaction.rs
  examples/outputs/native_tokens.rs
  examples/outputs/nft.rs
  examples/quorum.rs
  examples/search_address.rs
  examples/send_all.rs
  examples/split_funds.rs
  examples/transaction.rs
Labels: network:shimmer

#1077 Get correct unlock address for nfts with expiration unlock condition
  src/api/block_builder/input_selection/output_data.rs
Labels: network:shimmer

#1087 Provide bytes for PostBlockRaw
  Cargo.toml
  src/error.rs
  src/message_interface/client_method.rs
  src/message_interface/message_handler.rs
Labels: network:shimmer

#1023 Feat/ledger nano
  Cargo.lock
  Cargo.toml
  examples/ledger_nano.rs
  examples/ledger_nano_transaction.rs
  src/error.rs
  src/secret/ledger_nano.rs
  src/secret/mod.rs
  src/secret/types.rs
Labels: network:shimmer
