Repository iotaledger/iota.rs, pull requests merged in 2022-04, with the labels that each got.

#884 Fix foundry example
  Cargo.lock
  Cargo.toml
  examples/outputs/foundry.rs
  src/api/message_builder/mod.rs
  src/api/message_builder/pow/mod.rs
  src/client.rs
Labels: network:shimmer

#886 Fix slog-stdlog compilation error
  Cargo.lock
  Cargo.toml
Labels: scope:dependencies, priority:0, type:fix

#888 Shimmer coin type
  documentation/docs/libraries/java/getting_started.md
  documentation/docs/libraries/rust/getting_started.md
  examples/01_get_info.rs
  examples/03_generate_addresses.rs
  examples/05_get_address_balance.rs
  examples/06_simple_message.rs
  examples/07_get_message_metadata.rs
  examples/08_data_message.rs
  examples/09_transaction.rs
  examples/10_mqtt.rs
  examples/client_config.rs
  examples/consolidation.rs
  examples/custom_inputs.rs
  examples/custom_parent.rs
  examples/custom_payload.rs
  examples/get_funds.rs
  examples/indexer.rs
  examples/ledger.rs
  examples/message_time.rs
  examples/offline_signing/0_address_generation.rs
  examples/offline_signing/1_transaction_preparation.rs
  examples/offline_signing/3_send_message.rs
  examples/output.rs
  examples/outputs/alias.rs
  examples/outputs/all.rs
  examples/outputs/all_automatic_input_selection.rs
  examples/outputs/basic.rs
  examples/outputs/foundry.rs
  examples/outputs/native_tokens.rs
  examples/outputs/nft.rs
  examples/quorum.rs
  examples/search_address.rs
  examples/send_all.rs
  examples/split_funds.rs
  examples/stronghold.rs
  examples/transaction.rs
  src/api/address.rs
  src/builder.rs
  src/constants.rs
  src/lib.rs
  tests/addresses.rs
  tests/signer.rs
Labels: network:shimmer

#899 Use `fern-logger` instead of `bee-common`
  Cargo.lock
  Cargo.toml
  bindings/java/Cargo.lock
  bindings/nodejs/native/Cargo.lock
  bindings/python/native/Cargo.lock
  bindings/wasm/native/Cargo.lock
  src/error.rs
  src/lib.rs
  src/utils.rs
Labels: scope:dependencies, priority:4, type:chore

#900 Add dummy test to fix Python CI
  bindings/python/native/tests/test_full_node_api.py
Labels: scope:python, network:shimmer

#906 Update required nodejs versions
  bindings/nodejs/README.md
  documentation/docs/libraries/nodejs/api_reference.md
Labels: network:shimmer

#905 Update required nodejs versions
  bindings/nodejs/README.md
  documentation/docs/libraries/nodejs/api_reference.md
Labels: network:mainnet

#907 Clean offline signing examples
  .env.example
  bindings/java/Cargo.lock
  bindings/java/examples/basic-app/src/main/java/org/example/ExampleApp.java
  bindings/java/examples/basic-app/src/test/java/org/example/LibraryTest.java
  bindings/java/native/src/classes/address.rs
  bindings/java/native/src/classes/client/balance.rs
  bindings/java/native/src/classes/message.rs
  bindings/java/native/src/classes/prepared.rs
  bindings/java/native/src/java_glue.rs.in
  bindings/nodejs/examples/offline_signing/example_prepared_transaction.json
  bindings/nodejs/lib/types/models.d.ts
  bindings/nodejs/native/src/classes/client/api.rs
  bindings/wasm/examples/offline_signing/example_prepared_transaction.json
  examples/03_generate_addresses.rs
  examples/05_get_address_balance.rs
  examples/09_transaction.rs
  examples/consolidation.rs
  examples/custom_inputs.rs
  examples/custom_remainder_address.rs
  examples/get_funds.rs
  examples/indexer.rs
  examples/offline_signing/0_address_generation.rs
  examples/offline_signing/1_transaction_preparation.rs
  examples/offline_signing/2_transaction_signing.rs
  examples/offline_signing/3_send_message.rs
  examples/output.rs
  examples/outputs/alias.rs
  examples/outputs/all.rs
  examples/outputs/all_automatic_input_selection.rs
  examples/outputs/basic.rs
  examples/outputs/foundry.rs
  examples/outputs/native_tokens.rs
  examples/outputs/nft.rs
  examples/quorum.rs
  examples/search_address.rs
  examples/send_all.rs
  examples/split_funds.rs
  examples/stronghold.rs
  src/api/address.rs
  src/api/message_builder/input_selection/manual.rs
  src/api/message_builder/transaction.rs
  src/api/types.rs
  src/message_interface/mod.rs
  src/signing/ledger.rs
  tests/addresses.rs
  tests/signer.rs
Labels: scope:misc, network:shimmer, priority:3, type:chore

#914 Move code of conduct to .github folder
  .github/CODE_OF_CONDUCT.md
Labels: scope:docs, priority:4, type:chore

#904 Fix `cargo doc`
  src/api/types.rs
  src/constants.rs
  src/node_manager/builder.rs
  src/signing/mnemonic.rs
Labels: scope:docs, type:chore

#910 Semantic validation after transaction signing
  examples/offline_signing/2_transaction_signing.rs
  examples/offline_signing/3_send_message.rs
  rustfmt.toml
  src/api/message_builder/mod.rs
  src/api/message_builder/transaction.rs
  src/client.rs
  src/constants.rs
  src/error.rs
  src/signing/mod.rs
Labels: scope:core, network:shimmer, priority:2, type:enhancement

#915 Simplifies and harmonizes API module paths
  examples/04_get_address_outputs.rs
  examples/05_get_address_balance.rs
  examples/custom_inputs.rs
  examples/custom_remainder_address.rs
  examples/indexer.rs
  examples/outputs/all.rs
  examples/outputs/foundry.rs
  examples/outputs/nft.rs
  examples/quorum.rs
  examples/send_all.rs
  src/api/consolidation.rs
  src/api/message_builder/input_selection/automatic.rs
  src/client.rs
  src/message_interface/client_method.rs
  src/node_api/core/mod.rs
  src/node_api/core/routes.rs
  src/node_api/high_level/address.rs
  src/node_api/indexer/mod.rs
  src/node_api/indexer/query_parameters.rs
  src/node_api/indexer/responses.rs
  src/node_api/indexer/routes.rs
  src/node_api/mod.rs
  tests/node_api.rs
Labels: scope:core, type:chore

#913 Use dtos in message_interface
  src/api/message_builder/mod.rs
  src/message_interface/client_method.rs
  src/message_interface/message_handler.rs
  src/message_interface/response_type.rs
Labels: network:shimmer

#917 Bump bee commit
  Cargo.lock
  Cargo.toml
Labels: scope:dependencies, type:chore

#918 Pass &[InputSigningData] to verify_semantic
  examples/offline_signing/3_send_message.rs
  src/api/message_builder/transaction.rs
Labels: scope:core, type:chore

#927 Update to latest milestone changes
  Cargo.lock
  Cargo.toml
  src/api/message_builder/transaction.rs
  src/client.rs
  src/constants.rs
  src/error.rs
Labels: scope:dependencies, network:shimmer, priority:2, type:chore

#929 Fix GenerateMessage
  src/message_interface/message_handler.rs
  src/message_interface/mod.rs
  src/message_interface/response_type.rs
Labels: network:shimmer

#923 Refactor input selection
  Cargo.lock
  Cargo.toml
  examples/outputs/foundry.rs
  src/api/message_builder/input_selection/automatic.rs
  src/api/message_builder/input_selection/manual.rs
  src/api/message_builder/input_selection/mod.rs
  src/api/message_builder/input_selection/native_token_helpers.rs
  src/api/message_builder/input_selection/output_data.rs
  src/api/message_builder/input_selection/remainder.rs
  src/api/message_builder/input_selection/types.rs
  src/api/message_builder/mod.rs
  src/api/message_builder/transaction.rs
  src/client.rs
  src/message_interface/response_type.rs
Labels: scope:core, network:shimmer, type:enhancement

#937 Simplify native tokens usage
  Cargo.lock
  Cargo.toml
  examples/05_get_address_balance.rs
  examples/send_all.rs
  src/api/message_builder/input_selection/mod.rs
  src/api/message_builder/input_selection/native_token_helpers.rs
  src/api/message_builder/input_selection/output_data.rs
  src/api/message_builder/input_selection/remainder.rs
  src/api/message_builder/input_selection/types.rs
  src/error.rs
  src/node_api/high_level/address.rs
Labels: scope:core, network:shimmer, type:chore

#935 More message interface methods
  src/api/address.rs
  src/message_interface/client_method.rs
  src/message_interface/message_handler.rs
  src/message_interface/response_type.rs
  tests/addresses.rs
Labels: network:shimmer, type:feature

#938 Update bee-ternary and nodejs binding
  Cargo.lock
  Cargo.toml
  bindings/nodejs/native/Cargo.lock
  bindings/nodejs/native/src/message_handler.rs
Labels: scope:dependencies, network:shimmer

#939 Use PreparedTransactionDataDto and make allow_burning optional
  src/api/message_builder/mod.rs
  src/api/types.rs
  src/message_interface/client_method.rs
  src/message_interface/message_handler.rs
  src/message_interface/response_type.rs
Labels: network:shimmer, type:fix

#941 Examples/prepared transaction data dto
  examples/offline_signing/0_address_generation.rs
  examples/offline_signing/1_transaction_preparation.rs
  examples/offline_signing/2_transaction_signing.rs
Labels: network:shimmer, type:enhancement

#922 Change Signer to SecretManager
  Cargo.toml
  examples/02_mnemonic.rs
  examples/03_generate_addresses.rs
  examples/05_get_address_balance.rs
  examples/09_transaction.rs
  examples/consolidation.rs
  examples/custom_inputs.rs
  examples/custom_remainder_address.rs
  examples/get_funds.rs
  examples/indexer.rs
  examples/ledger.rs
  examples/offline_signing/0_address_generation.rs
  examples/offline_signing/2_transaction_signing.rs
  examples/output.rs
  examples/outputs/alias.rs
  examples/outputs/all.rs
  examples/outputs/all_automatic_input_selection.rs
  examples/outputs/basic.rs
  examples/outputs/foundry.rs
  examples/outputs/native_tokens.rs
  examples/outputs/nft.rs
  examples/quorum.rs
  examples/search_address.rs
  examples/send_all.rs
  examples/split_funds.rs
  examples/stronghold.rs
  examples/transaction.rs
  src/api/address.rs
  src/api/consolidation.rs
  src/api/message_builder/input_selection/automatic.rs
  src/api/message_builder/input_selection/manual.rs
  src/api/message_builder/input_selection/mod.rs
  src/api/message_builder/input_selection/output_data.rs
  src/api/message_builder/input_selection/remainder.rs
  src/api/message_builder/mod.rs
  src/api/message_builder/transaction.rs
  src/api/types.rs
  src/client.rs
  src/error.rs
  src/lib.rs
  src/message_interface/client_method.rs
  src/message_interface/message_handler.rs
  src/message_interface/mod.rs
  src/secret/ledger.rs
  src/secret/mnemonic.rs
  src/secret/mod.rs
  src/secret/stronghold.rs
  src/secret/types.rs
  src/signing/ledger.rs
  src/signing/mod.rs
  src/stronghold/mod.rs
  src/stronghold/secret.rs
  tests/addresses.rs
  tests/node_api.rs
  tests/secret_manager.rs
  tests/signer.rs
Labels: scope:core, network:shimmer, type:refactor

#807 Docs - Edit with Style Guide and Implement Diataxis
  documentation/.gitignore
  documentation/docs/contribute.md
  documentation/docs/getting_started.md
  documentation/docs/libraries/nodejs/getting_started.md
  documentation/docs/libraries/overview.md
  documentation/docs/libraries/rust/getting_started.md
  documentation/docs/overview.md
  documentation/docs/specs.md
  documentation/docs/theme/book.js
  documentation/docs/theme/css/chrome.css
  documentation/docs/theme/css/custom/header.css
  documentation/docs/theme/css/general.css
  documentation/docs/theme/css/print.css
  documentation/docs/theme/css/variables.css
  documentation/docs/theme/favicon.png
  documentation/docs/theme/header.hbs
  documentation/docs/theme/highlight.css
  documentation/docs/theme/highlight.js
  documentation/docs/theme/index.hbs
  documentation/docs/troubleshooting.md
  documentation/docs/welcome.md
  documentation/package-lock.json
  documentation/package.json
Labels: scope:docs

#946 Remove GetAddressesBuilder::default
  src/api/address.rs
Labels: scope:core, network:shimmer, priority:4, type:chore

#947 Fix warnings and compilation error
  examples/10_mqtt.rs
  src/secret/mod.rs
Labels: scope:core, network:shimmer, priority:3, type:fix

#950 Use amount as String to prevent overflow issues
  src/api/message_builder/mod.rs
Labels: network:shimmer, type:enhancement

#952 Add MessageId client method
  src/client.rs
  src/message_interface/client_method.rs
  src/message_interface/message_handler.rs
  src/message_interface/mod.rs
  src/message_interface/response_type.rs
Labels: network:shimmer, type:feature

#955 Update bee revs to fix nodeinfo
  Cargo.lock
  Cargo.toml
  src/api/message_builder/transaction.rs
  src/client.rs
Labels: network:shimmer

#951 Fix Workflows
  .github/workflows/examine-core.yml
  .github/workflows/examine-python-bindings.yml
  Cargo.toml
  examples/10_mqtt.rs
  examples/custom_remainder_address.rs
  examples/offline_signing/2_transaction_signing.rs
  examples/offline_signing/3_send_message.rs
  examples/output.rs
  examples/outputs/alias.rs
  examples/outputs/all.rs
  examples/outputs/all_automatic_input_selection.rs
  examples/outputs/basic.rs
  examples/outputs/foundry.rs
  examples/outputs/native_tokens.rs
  examples/outputs/nft.rs
  src/api/message_builder/mod.rs
  src/api/message_builder/pow/mod.rs
  src/builder.rs
  src/client.rs
  src/constants.rs
  src/error.rs
  src/message_interface/client_method.rs
  src/message_interface/mod.rs
  src/message_interface/response_type.rs
  src/node_api/core/mod.rs
  src/node_api/core/routes.rs
  src/node_api/mqtt/mod.rs
  src/node_manager/http_client.rs
  src/node_manager/mod.rs
Labels: scope:ci, type:fix

#961 Update indexer routes
  bindings/java/native/src/classes/client/full_node_api.rs
  bindings/java/native/src/java_glue.rs.in
  bindings/wasm/docs/api-reference.md
  bindings/wasm/native/src/client.rs
  documentation/docs/libraries/java/api_reference.md
  documentation/docs/libraries/wasm/api_reference.md
  src/client.rs
  src/node_api/indexer/routes.rs
Labels: scope:core, network:shimmer
